[build]
  publish = "public"

[functions]
  directory = "netlify/functions"
  node_bundler = "esbuild"

# Intestazioni di sicurezza per il sito
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "same-origin"
    X-Robots-Tag = "noindex, nofollow"
